import { Panel } from '@stixmagic/ui';
import { loadPipelineManifest } from '../integrations/manifest';
import { PackCatalogExplorer } from './PackCatalogExplorer';

export default async function PacksPage() {
  const manifest = await loadPipelineManifest();
  const packs = manifest.packs;

  return (
    <div className="space-y-8 pb-10">
      <Panel>
        <span className="inline-flex rounded-full border border-white/10 bg-panel-secondary px-4 py-1 text-xs font-medium text-accent-cyan">
          Pack Catalog
        </span>
        <h1 className="mt-5 text-4xl font-semibold tracking-tight text-text sm:text-5xl">
          Browse STIXMΛGIC packs.
        </h1>
        <p className="mt-4 max-w-3xl text-base leading-relaxed text-muted">
          Curated asset collections generated by the STIXMΛGIC pipeline. Each pack includes multiple assets with
          metadata, format variants, and preview support.
        </p>
      </Panel>

      <div>
        {packs.length === 0 ? (
          <Panel variant="secondary">
            <div className="py-6 text-center">
              <p className="text-2xl" aria-hidden="true">📦</p>
              <p className="mt-3 text-sm font-medium text-text">No packs available</p>
              <p className="mt-1 text-sm text-muted">
                Asset packs will appear here once the pipeline manifest is populated.
              </p>
            </div>
          </Panel>
        ) : (
          <PackCatalogExplorer packs={packs} />
        )}
      </div>

      <Panel variant="secondary">
        <h2 className="text-xl font-semibold text-text">Pipeline-generated</h2>
        <p className="mt-3 text-sm leading-relaxed text-muted">
          All packs are produced by the STIXMΛGIC bot pipeline. Pack metadata, asset counts, and format availability are
          read from pipeline manifests. As new packs are generated, they appear here automatically.
        </p>
        <p className="mt-2 text-xs text-muted/60">
          Manifest version: <span className="font-mono text-accent-cyan">{manifest.version}</span>
        </p>
      </Panel>
    </div>
  );
}
