import { PackGrid, Panel, Tabs } from '@stixmagic/ui';
import { loadPipelineManifest } from '../integrations/manifest';

const categoryTabs = [
  {
    id: 'all',
    label: 'All Packs',
    content:
      'Browse all available MagicStix packs across categories. Each pack includes multiple assets in supported export formats.'
  },
  {
    id: 'motion',
    label: 'Motion',
    content: 'Animated letter sets, looping motion presets, and kinetic character packs for streams and overlays.'
  },
  {
    id: 'signals',
    label: 'Signals & Neon',
    content: 'Glowing neon symbols, arrow signals, and indicator assets built for live production screens.'
  },
  {
    id: 'overlays',
    label: 'Overlays',
    content: 'Transparent WebM overlay assets ready for OBS, Streamlabs, and production scene layers.'
  }
];

export default async function PacksPage() {
  const manifest = await loadPipelineManifest();
  const packs = manifest.packs;

  return (
    <div className="space-y-8 pb-10">
      <Panel>
        <span className="inline-flex rounded-full border border-white/10 bg-panel-secondary px-4 py-1 text-xs font-medium text-accent-cyan">
          Pack Catalog
        </span>
        <h1 className="mt-5 text-4xl font-semibold tracking-tight text-text sm:text-5xl">
          Browse MagicStix packs.
        </h1>
        <p className="mt-4 max-w-3xl text-base leading-relaxed text-muted">
          Curated asset collections generated by the MagicStix pipeline. Each pack includes multiple assets with
          metadata, format variants, and preview support.
        </p>
      </Panel>

      <Tabs items={categoryTabs} />

      <div>
        <div className="mb-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold text-text">All packs</h2>
          <span className="text-sm text-muted">{packs.length} packs</span>
        </div>
        <PackGrid packs={packs} />
      </div>

      <Panel variant="secondary">
        <h2 className="text-xl font-semibold text-text">Pipeline-generated</h2>
        <p className="mt-3 text-sm leading-relaxed text-muted">
          All packs are produced by the MagicStix bot pipeline. Pack metadata, asset counts, and format availability are
          read from pipeline manifests. As new packs are generated, they appear here automatically.
        </p>
        <p className="mt-2 text-xs text-muted/60">
          Manifest version: <span className="font-mono text-accent-cyan">{manifest.version}</span>
        </p>
      </Panel>
    </div>
  );
}

