import { GalleryGrid, Panel, Tabs } from '@stixmagic/ui';
import { loadPipelineManifest } from '../integrations/manifest';

const filterTabs = [
  {
    id: 'all',
    label: 'All Assets',
    content: 'All MagicStix preview assets across packs and categories. GIF and WebM previews where available.'
  },
  {
    id: 'animated',
    label: 'Animated',
    content: 'Assets with looping animation — GIF and WebM exports ready for sticker packs and streaming overlays.'
  },
  {
    id: 'overlay',
    label: 'Overlays',
    content: 'Transparent WebM overlay assets optimized for OBS and Streamlabs live production scenes.'
  },
  {
    id: 'letters',
    label: 'Letters',
    content: 'Motion Alphabet assets — animated A–Z character renders with neon and motion style variants.'
  }
];

export default async function GalleryPage() {
  const manifest = await loadPipelineManifest();
  const assets = manifest.assets;

  return (
    <div className="space-y-8 pb-10">
      <Panel>
        <span className="inline-flex rounded-full border border-white/10 bg-panel-secondary px-4 py-1 text-xs font-medium text-accent-cyan">
          Preview Gallery
        </span>
        <h1 className="mt-5 text-4xl font-semibold tracking-tight text-text sm:text-5xl">Asset gallery.</h1>
        <p className="mt-4 max-w-3xl text-base leading-relaxed text-muted">
          Browse individual MagicStix assets with GIF and WebM previews, format tags, and pack metadata. All assets are
          generated by the MagicStix pipeline.
        </p>
      </Panel>

      <Tabs items={filterTabs} />

      <div>
        <div className="mb-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold text-text">All previews</h2>
          <span className="text-sm text-muted">{assets.length} assets</span>
        </div>
        <GalleryGrid assets={assets} />
      </div>

      <Panel variant="secondary">
        <h2 className="text-xl font-semibold text-text">Preview availability</h2>
        <p className="mt-3 text-sm leading-relaxed text-muted">
          Preview assets are loaded from the MagicStix pipeline manifest. As the bot pipeline generates new assets, they
          appear here with their associated GIF and WebM previews.
        </p>
        <p className="mt-2 text-xs text-muted/60">
          Manifest version: <span className="font-mono text-accent-cyan">{manifest.version}</span>
        </p>
      </Panel>
    </div>
  );
}

