import { Panel } from '@stixmagic/ui';
import { loadPipelineManifest } from '../integrations/manifest';
import { AssetGalleryExplorer } from './AssetGalleryExplorer';

export default async function GalleryPage() {
  const manifest = await loadPipelineManifest();
  const assets = manifest.assets;

  return (
    <div className="space-y-8 pb-10">
      <Panel>
        <span className="inline-flex rounded-full border border-white/10 bg-panel-secondary px-4 py-1 text-xs font-medium text-accent-cyan">
          Preview Gallery
        </span>
        <h1 className="mt-5 text-4xl font-semibold tracking-tight text-text sm:text-5xl">Asset gallery.</h1>
        <p className="mt-4 max-w-3xl text-base leading-relaxed text-muted">
          Browse individual STIXMΛGIC assets with GIF and WebM previews, format tags, and pack metadata. All assets are
          generated by the STIXMΛGIC pipeline.
        </p>
      </Panel>

      <div>
        {assets.length === 0 ? (
          <Panel variant="secondary">
            <div className="py-6 text-center">
              <p className="text-2xl" aria-hidden="true">🖼️</p>
              <p className="mt-3 text-sm font-medium text-text">No previews available</p>
              <p className="mt-1 text-sm text-muted">
                Preview assets will appear here once the pipeline manifest is populated.
              </p>
            </div>
          </Panel>
        ) : (
          <AssetGalleryExplorer assets={assets} />
        )}
      </div>

      <Panel variant="secondary">
        <h2 className="text-xl font-semibold text-text">Preview availability</h2>
        <p className="mt-3 text-sm leading-relaxed text-muted">
          Preview assets are loaded from the STIXMΛGIC pipeline manifest. As the bot pipeline generates new assets, they
          appear here with their associated GIF and WebM previews.
        </p>
        <p className="mt-2 text-xs text-muted/60">
          Manifest version: <span className="font-mono text-accent-cyan">{manifest.version}</span>
        </p>
      </Panel>
    </div>
  );
}
