import { FeatureGrid, Hero, HeroAssetShowcase, Panel, Tabs } from '@stixmagic/ui';

const features = [
  {
    tag: 'Motion Alphabet',
    title: 'Animated letter packs',
    description: 'A–Z letters rendered as looping GIFs, WebMs, and overlay-ready assets for any production workflow.'
  },
  {
    tag: 'Sticker Engine',
    title: 'Visual asset pipeline',
    description:
      'The MagicStix bot pipeline generates stickers, animated emojis, signals, and overlays as production-ready exports.'
  },
  {
    tag: 'Pack Catalog',
    title: 'Modular asset packs',
    description:
      'Browse curated packs — DJ sets, neon signals, cloud motifs, emoji reactions, and more — ready to drop into any stream or chat.'
  },
  {
    tag: 'Generator UI',
    title: 'Custom text preview',
    description:
      'Choose a style, type your text, and preview animated output before exporting. Generator frontend coming soon.'
  }
];

const statusTabs = [
  {
    id: 'vision',
    label: 'Vision',
    content:
      'MagicStix is a modular visual system that turns text, symbols, and expressions into animated assets — stickers, overlays, letters, and packs — generated by a pipeline and displayed here for preview, download, and customization.'
  },
  {
    id: 'ecosystem',
    label: 'Ecosystem',
    content:
      'The MagicStix bot repo handles asset generation, animation export, and pack production. This web repo is the presentation layer: catalog, previews, generator frontend, and future storefront — consuming outputs from the pipeline.'
  },
  {
    id: 'status',
    label: 'Status',
    content:
      'Ecosystem site launched with landing, pack catalog, preview gallery, and generator scaffolding. Pipeline integration boundary is defined and ready for live asset consumption as the bot pipeline matures.'
  }
];

export default function HomePage() {
  return (
    <div className="space-y-8 pb-10">
      <Hero
        badge="MagicStix Visual Ecosystem"
        title="Animated assets for every moment."
        subtitle="Stickers, animated letters, symbols, overlays, and packs — generated by a modular pipeline and ready for streaming, chat, and creative production."
        primaryCta="Browse Pack Catalog"
        secondaryCta="Explore the Ecosystem"
        previewSlot={<HeroAssetShowcase />}
      />

      <FeatureGrid items={features} />

      <section className="grid gap-4 lg:grid-cols-2">
        <Panel>
          <h2 className="text-xl font-semibold text-text">What is MagicStix?</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted">
            MagicStix is a modular visual asset system. The bot pipeline generates stickers, animated letters, neon
            signals, and overlay packs. This site is the public face of that ecosystem — preview, catalog, and future
            generator frontend.
          </p>
        </Panel>
        <Panel variant="secondary">
          <h2 className="text-xl font-semibold text-text">Built for creators</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted">
            Stream overlays, chat stickers, animated name packs, DJ visuals, and emoji sets — all generated at quality
            from a single pipeline and downloadable in GIF, WebM, WebP, and more.
          </p>
        </Panel>
      </section>

      <Tabs items={statusTabs} />
    </div>
  );
}
