import Link from 'next/link';
import { Panel } from '@stixmagic/ui';

export default function PackNotFound() {
  return (
    <div className="space-y-6 pb-10">
      <Panel>
        <span className="inline-flex rounded-full border border-white/10 bg-panel-secondary px-4 py-1 text-xs font-medium text-muted">
          Not Found
        </span>
        <h1 className="mt-5 text-3xl font-semibold tracking-tight text-text">Pack not found.</h1>
        <p className="mt-3 max-w-xl text-sm leading-relaxed text-muted">
          This pack ID does not exist in the current manifest. It may have been renamed, removed, or not yet generated by
          the pipeline.
        </p>
        <div className="mt-6">
          <Link
            href="/packs"
            className="inline-flex rounded-xl bg-accent-primary px-5 py-2.5 text-sm font-semibold text-text transition hover:opacity-90"
          >
            Browse all packs
          </Link>
        </div>
      </Panel>
    </div>
  );
}
